language: node_js

node_js:
  - '6'

cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-the-Chrome-addon-in-the-headless-mode
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:4200 &

script:
  - yarn test:ci
  - yarn e2e:ci
  - yarn build:dist
  - yarn build:demo
  - yarn typedoc

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

notifications:
  email: false
